name: game_sambung_kata
description: "Game Sambung Kata - Modern & Beautiful"
publish_to: 'none'
version: 1.8.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  google_fonts: ^6.1.0
  audioplayers: ^5.2.1
  http: ^1.2.1
  ota_update: ^7.0.0
  archive: ^3.6.1
  path_provider: ^2.1.3
  app_links: ^6.3.2
  package_info_plus: ^8.0.0
  network_info_plus: ^6.0.0
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/audio/benar.mp3
    - assets/audio/salah.wav
    - assets/audio/menang.mp3
    - assets/audio/kalah.mp3
    - assets/audio/lobby.wav
    - assets/audio/typing1.wav
    - assets/audio/typing2.wav
    - assets/audio/ingame/
    - assets/images/background.png
    - assets/data/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
